language: node_js
node_js:
  - lts/*
notifications:
  email:
    on_success: never
    on_failure: always
sudo: false
dist: trusty
branches:
  only:
  - master
env:
  global:
    - CI=false
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master