language: node_js
node_js:
  - lts/*
notifications:
  email:
    on_success: never
    on_failure: always
sudo: false
dist: trusty
branches:
  only:
  - master
before_install:
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
script:
  - npm install
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master