language: node_js
node_js:
  - lts/*
notifications:
  email:
    on_success: never
    on_failure: always
services:
  - postgres
addons:
  postgresql: "9.6"
sudo: false
dist: trusty
branches:
  only:
  - master
env:
  global:
    - PG_CONNECTION_STRING=postgres://postgres:postgres@localhost:5432/travis_ci_test
    - TIMEOUT=20000
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
before_install:
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
install:
  - travis_retry npm install
test:
  - npm test
before_deploy:
  - npm run coverage
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master